name: elevation
root: .

windows:
  - main:
      layout: main-vertical
      panes:
        - e .
        - yarn run parcel index.html
        - docker run -t -i -v $(pwd)/data:/code/data -p 8081:8080 openelevation/open-elevation
        -
